sudo: required

language: generic

services:
    - docker
    
after_success:
    - docker build -t kamarsu/flask-image ./flsk
    - docker build -t kamarsu/nginx-image ./nginx
    # Log-in to the Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push the images to Docker hub
    -docker push kamarsu/flask-image
    -docker push kamarsu/nginx-image
    
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "salary_predictor"
    env: "SalaryPredictor-env"
    bucket_name: "elasticbeanstalk-us-east-2-858669094415"
    bucket_path: "salary_predictor"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    